# reference: https://github.com/marketplace/actions/electron-builder-action

name: Release

on: push

jobs:
  Release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install alsa and pulse audio on linux
        run: if ["$RUNNER_OS" = "Linux"]; then sudo apt-get install libasound2 libasound2-dev libpulse-dev ; fi

      # TODO: build tensorflow library
      
      - name: Build binaries
        run: |
          yarn add run-script-os
          yarn run build-binaries

      # TODO: download a tflite model from s3

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}